### ISSUE TITLE
Error fixed in Unit test

### ISSUE THREAD

**Issue by simonpascal** [hdiv/spring-boot-starter-hdiv#1]
`org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration;` instead 
`org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration;`   
`import org.hdiv.util.Method;`
`config.isStartPage("/", Method.GET)` instead `config.isStartPage("/", "get")`

**Comment by gillarramendi** [comment]
Tests fixed in release 1.2.0.
Thanks
