### ISSUE TITLE
cannot change default _HDIV_STATE_ name

### ISSUE THREAD

**Issue by simonpascal** [hdiv/spring-boot-starter-hdiv#2]
I want to change the _default HDIV_STATE_  name.  
we see this message:
**************************************************************
*                                                            *
*       This feature is no longer supported under Hdiv CE    *
*                                                            *
**************************************************************
Feature:StateParameterName

there are vulnerability when we change name of parameter?

**Comment by gillarramendi** [comment]
This feature is supported only in the Enterprise Edition. Feel free to contact us at contact@hdivsecurity.com.
